"""Data models for the autonomous video production pipeline.

Defines all data structures used across the video agent system:
script generation, TTS/timing, timeline composition, and draft review.
"""

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import List, Optional


class VisualType(Enum):
    """Type of visual asset for a scene."""

    BROLL_VIDEO = "broll_video"
    GENERATED_IMAGE = "generated_image"
    TEXT_GRAPHIC = "text_graphic"


class SubtitleStyle(Enum):
    """Subtitle rendering style preset."""

    HORMOZI = "hormozi"  # Bold, high-contrast, word-by-word highlight
    DOCUMENTARY = "documentary"  # Clean lower-third, sentence-based
    MINIMAL = "minimal"  # Small, unobtrusive captions


@dataclass
class HookScript:
    """Opening hook segment of the video script.

    The hook is the first 5-15 seconds designed to capture attention.
    """

    voiceover: str  # Narration text for TTS
    visual_description: str  # What the viewer should see
    visual_keywords: List[str]  # Search terms for B-roll/image lookup
    sound_effect: str = "none"  # Optional SFX cue


@dataclass
class SceneScript:
    """A single scene within the video script.

    Each scene represents a logical segment with its own voiceover,
    visual direction, and timing estimate.
    """

    id: int  # Sequential scene number
    duration_est: float  # Estimated duration in seconds
    voiceover: str  # Narration text for TTS
    visual_keywords: List[str]  # Search terms for asset lookup
    visual_style: str  # Style hint (e.g., "cinematic", "documentary")
    visual_type: VisualType  # Asset type to acquire
    transition_in: str = "cut"  # Transition from previous scene
    music_mood: str = "neutral"  # Music mood cue
    sound_effect: str = "none"  # Optional SFX cue
    min_clip_duration: Optional[float] = None  # Minimum B-roll clip length (seconds)
    max_clip_duration: Optional[float] = None  # Maximum B-roll clip length (seconds)


@dataclass
class Script:
    """Complete video script generated by AI.

    Contains the hook, all scenes, and metadata about the video.
    """

    title: str  # Video title
    hook: HookScript  # Opening hook segment
    scenes: List[SceneScript]  # Ordered list of scenes
    metadata: dict  # Flexible metadata (topic, style, audience, etc.)


@dataclass
class WordTiming:
    """Word-level timing from TTS or speech recognition.

    Used for precise subtitle rendering and visual sync.
    """

    word: str  # The spoken word
    start: float  # Start time in seconds
    end: float  # End time in seconds
    confidence: float = 1.0  # Recognition/alignment confidence (0-1)


@dataclass
class TimelineScene:
    """A scene placed on the video timeline with resolved assets.

    Represents a fully-resolved scene with actual file paths and
    precise timing information ready for FFmpeg composition.
    """

    scene_id: int  # Matches SceneScript.id
    audio_path: Path  # Path to TTS audio file
    audio_start: float  # Start time in the master audio track
    audio_end: float  # End time in the master audio track
    visual_path: Path  # Path to visual asset (video clip or image)
    visual_type: VisualType  # Type of visual asset
    transition: str = "cut"  # Transition from previous scene
    sound_effect: str = "none"  # SFX cue (e.g., "whoosh", "typing")
    word_timings: List[WordTiming] = field(default_factory=list)


@dataclass
class Timeline:
    """Complete video timeline ready for FFmpeg rendering.

    Aggregates all scenes with their resolved assets, plus global
    tracks for music, subtitles, and color grading.
    """

    scenes: List[TimelineScene]  # Ordered scenes with resolved assets
    master_audio: Path  # Path to concatenated voiceover audio
    music_path: Optional[Path] = None  # Background music track
    subtitle_path: Optional[Path] = None  # Subtitle file (.srt/.ass)
    color_grade: str = "dark_cinematic"  # Color grading preset name
    total_duration: float = 0.0  # Total timeline duration in seconds


@dataclass
class FixRequest:
    """A specific issue found during draft review.

    Describes what's wrong with a scene and how to fix it.
    """

    scene_id: int  # Scene that needs fixing
    issue_type: str  # "visual_mismatch" | "pacing" | "audio" | "content_gap"
    description: str  # Human-readable description of the issue
    suggested_keywords: List[str] = field(default_factory=list)  # Alt search terms
    suggested_fix: str = ""  # How to resolve the issue
    priority: str = "medium"  # "low" | "medium" | "high"


@dataclass
class DraftReview:
    """AI review of a rendered draft video.

    Contains scoring, fix requests, and approval status for the
    iterative refinement loop.
    """

    overall_score: int  # 1-10 quality rating
    fix_requests: List[FixRequest]  # Issues to address
    approved: bool  # Whether the draft passes quality threshold
    iteration: int = 0  # Which review iteration this is
    notes: str = ""  # General reviewer notes


@dataclass
class VisualTypeDecision:
    """Director's decision on visual type for a scene.

    The director analyzes both photo and video candidates
    and decides which type best serves the scene's narrative.
    """

    scene_id: int  # Scene this decision applies to
    chosen_type: VisualType  # BROLL_VIDEO or GENERATED_IMAGE
    confidence: float  # 0.0-1.0 confidence in decision
    rationale: str  # Why this type was chosen


__all__ = [
    # Enums
    "VisualType",
    "SubtitleStyle",
    # Script models
    "HookScript",
    "SceneScript",
    "Script",
    # Timeline models
    "WordTiming",
    "TimelineScene",
    "Timeline",
    # Review models
    "FixRequest",
    "DraftReview",
    "VisualTypeDecision",
]
