"""Data models for user B-roll preferences and interactive questions."""

from dataclasses import dataclass, field
from typing import Optional, List


@dataclass
class UserPreferences:
    """User preferences for B-roll style and content."""

    # Visual style preferences
    visual_style: Optional[str] = None  # e.g., "cinematic", "documentary", "vintage", "modern"
    color_mood: Optional[str] = None  # e.g., "warm", "cold", "neutral", "vibrant"

    # Temporal preferences
    time_of_day: Optional[str] = None  # e.g., "any", "daytime", "night", "golden hour"
    era_period: Optional[str] = None  # e.g., "modern", "historical", "1980s"

    # Content preferences
    location_type: Optional[str] = None  # e.g., "urban", "nature", "indoor", "mixed"
    pace: Optional[str] = None  # e.g., "fast", "slow", "medium"
    content_focus: Optional[str] = None  # e.g., "people", "objects", "landscapes", "abstract"

    # Existing filter (integrate with current content_filter)
    content_filter: Optional[str] = None  # e.g., "men only, no women"

    # Custom preferences from open questions
    custom_notes: List[str] = field(default_factory=list)

    def to_prompt_instructions(self) -> str:
        """Convert preferences to prompt instructions for AI.

        Returns:
            Formatted string with user preferences for AI prompt injection.
        """
        instructions = []

        if self.visual_style:
            instructions.append(f"Visual style: {self.visual_style}")
        if self.color_mood:
            instructions.append(f"Color/mood preference: {self.color_mood}")
        if self.time_of_day:
            instructions.append(f"Time of day: {self.time_of_day}")
        if self.era_period:
            instructions.append(f"Era/period: {self.era_period}")
        if self.location_type:
            instructions.append(f"Location type: {self.location_type}")
        if self.pace:
            instructions.append(f"Pacing: {self.pace}")
        if self.content_focus:
            instructions.append(f"Content focus: {self.content_focus}")
        if self.content_filter:
            instructions.append(f"Content filter: {self.content_filter}")
        if self.custom_notes:
            instructions.append(f"Additional notes: {'; '.join(self.custom_notes)}")

        return "\n".join(instructions) if instructions else ""

    def has_preferences(self) -> bool:
        """Check if any preferences have been set.

        Returns:
            True if at least one preference is set, False otherwise.
        """
        return any([
            self.visual_style,
            self.color_mood,
            self.time_of_day,
            self.era_period,
            self.location_type,
            self.pace,
            self.content_focus,
            self.content_filter,
            self.custom_notes
        ])


@dataclass
class GeneratedQuestion:
    """A context-aware question generated by AI."""

    question_id: str  # Unique identifier for mapping answer back
    question_text: str  # The question to ask user
    preference_field: str  # Which UserPreferences field this maps to
    options: Optional[List[str]] = None  # Pre-defined options (if any)
    allows_custom: bool = True  # Whether user can provide custom answer
    context_reason: Optional[str] = None  # Why AI generated this question
